create or replace table workspace.silver.listing_details as
select 
cast(id AS BIGINT) as id,
cast(listing_url AS STRING) as listing_url,
cast(scrape_id AS STRING) as scrape_id,
cast(last_scraped AS TIMESTAMP) as last_scraped,
cast(source AS STRING) as source,
cast(name AS STRING) as name,
cast(description AS STRING) as description,
cast(neighborhood_overview AS STRING) as neighborhood_overview,
picture_url,
host_id,
host_url,
host_name,
host_since,
host_location,
host_about,
host_response_time,
host_response_rate,
host_acceptance_rate,
host_is_superhost,
host_thumbnail_url,
host_picture_url,
host_neighbourhood,
host_listings_count,
host_total_listings_count,
host_verifications,
host_has_profile_pic,
host_identity_verified,
neighbourhood,
neighbourhood_cleansed,
neighbourhood_group_cleansed,
latitude,
longitude,
property_type,
room_type,
accommodates,
bathrooms,
bathrooms_text,
bedrooms,
beds,
amenities,
price,
minimum_nights,
maximum_nights,
minimum_minimum_nights,
maximum_minimum_nights,
minimum_maximum_nights,
maximum_maximum_nights,
minimum_nights_avg_ntm,
maximum_nights_avg_ntm,
calendar_updated,
has_availability,
availability_30,
availability_60,
availability_90,
availability_365,
calendar_last_scraped,
number_of_reviews,
number_of_reviews_ltm,
first_review,
last_review,
review_scores_rating,
review_scores_accuracy,
review_scores_cleanliness,
review_scores_checkin,
review_scores_communication,
review_scores_location,
review_scores_value,
calculated_host_listings_count,
calculated_host_listings_count_entire_homes,
calculated_host_listings_count_private_rooms,
calculated_host_listings_count_shared_rooms,
reviews_per_month,
city
from workspace.bronze.listing_details 
WHERE try_cast(id AS BIGINT) IS NOT NULL
AND try_cast(host_id AS BIGINT) IS NOT NULL;